sing in
Mohammed4mach/Recipehub-project pull request #25
Opened 2022-04-25 18:53 UTC by Amrmamlook

2022-04-26 09:20 UTC, Mohammed4mach requested changes
Placeholder color of the input make it difficult to read, please change it besides the requested changes with each file.

2022-04-26 09:20 UTC, Mohammed4mach commented on sign in/sing up.html
> +    <title>
### Title tag should not be empty

2022-04-26 09:20 UTC, Mohammed4mach commented on sign in/sing up.html
> +        <img src="icons8-user-64.png">
### It is recommended to use alt attribute with img tag with descriptive description of the image

2022-04-26 09:20 UTC, Mohammed4mach commented on sign in/sing up.html
> +<html>
### \<\!DOCTYPE html\> is missing
This tag is important. It Provide information to the browser including the type of the document and how the browser will render the content.
[What is the DOCTYPE Declaration in HTML?](https://www.freecodecamp.org/news/what-is-the-doctype-declaration-in-html/#:~:text=The%20HTML%20document%20type%20declaration,way%20by%20different%20web%20browsers.)

2022-04-26 09:20 UTC, Mohammed4mach commented on sign in/sing up.html
> +            <p></p>
### \<p\> tag should not be empty
If it is empty, so it is useless. Please delete or fill with meaningful data.
same problem at line 26

2022-04-26 09:20 UTC, Mohammed4mach commented on sign in/sing up.html
> +</html>
### It is recommended to have a new line character at the end of the file

2022-04-26 09:20 UTC, Mohammed4mach commented on sign in/style.css
> +
### It is bad practice to leave empty lines before finishing the selector style
Same problem in lines 36, 43, 44, 45, 62, 63, 72, 83 and 99

2022-04-26 09:20 UTC, Mohammed4mach commented on sign in/style.css
> +
### One new line is enough
Line 106 is enough as empty line at the end of the file.
Lines 107, 108 and 109 is not necessary.

2022-04-26 13:58 UTC, Amrmamlook commented on sign in/sing up.html
> +        <img src="icons8-user-64.png">
<img src="icons8-user-64.png" alt =" user _ icon">

2022-04-26 13:58 UTC, Amrmamlook commented on sign in/sing up.html
> +    <title>
delete the title lol

2022-04-26 14:03 UTC, Amrmamlook commented on sign in/sing up.html
> +    <title>
delete it

2022-04-28 12:34 UTC, Mohammed4mach requested changes

2022-04-28 12:34 UTC, Mohammed4mach commented on sing in.html
> +
### Title tag is missing
Please put in a title tag with descriptive title.

[More about importance of title tag](https://moz.com/learn/seo/title-tag#:~:text=Why%20are%20title%20tags%20important,your%20page%20via%20organic%20search.)

2022-04-28 12:34 UTC, Mohammed4mach commented on sing in.html
> +
### Title tag is missing
Please put in a title tag with descriptive title.

[More about importance of title tag](https://moz.com/learn/seo/title-tag#:~:text=Why%20are%20title%20tags%20important,your%20page%20via%20organic%20search.)

2022-04-28 12:34 UTC, Mohammed4mach commented on sing in.html
> +<html>
### \<\!DOCTYPE html\> is missing
This tag provide information and rules to browsers to render page content.
Forget it and you will encounter UNPREDICTED rendering.

[More about this tag](https://graybox.co/knowledge/blog/the-importance-of-the-doctype#:~:text=Per%20HTML%20and%20XHTML%20standards,correctly%20or%20validate%20without%20them.)

2022-04-28 12:34 UTC, Mohammed4mach commented on style.css
> +
### One new line at the end of a file is enough
Delete Lines 101, 102 and 103

2022-04-28 12:34 UTC, Mohammed4mach commented on style.css
> +
### One new line at the end of a file is enough
Delete Lines 101, 102 and 103

2022-04-28 12:34 UTC, Mohammed4mach commented on sing in.html
> +</html>
### It is recommended to have a new line character at the end of the file
[Check why..](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

2022-04-28 12:34 UTC, Mohammed4mach commented on style.css
> +
### It is bad practice to leave empty lines before finishing the selector style

Same problem at lines 37, 38, 39, 56, 57, 66, 78 and 93

2022-04-30 12:42 UTC, merged