Add files via upload
Mohammed4mach/Recipehub-project pull request #27
Opened 2022-04-26 14:03 UTC by ManarMagdy

2022-04-30 09:43 UTC, Mohammed4mach requested changes
Few changes are required

2022-04-30 09:43 UTC, Mohammed4mach commented on MasterDesign.html
> +</html>
### It is recommended to have a new line character at the end of the file

[Check why](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

2022-04-30 09:43 UTC, Mohammed4mach commented on Master.css
> +/*end footer*/
### It is recommended to have a new line character at the end of the file

[Check why](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

2022-04-30 09:43 UTC, Mohammed4mach commented on Master.css
> +    height: 3000px;
### Don't Set height to a specific value

This will affect the view badly causing unpredicted rendering behavior, especially when the page rendered dynamically.

Instead, you can replace this line with `min-height: 100vh;`. This will set minimum height of the body to 100% of screen view.

2022-04-30 09:43 UTC, Mohammed4mach commented on Master.css
> +.fa-solid fa-bars{
### Class name isn't used in HTML

`.fa-solid fa-bars{`
This line has two problems:
- You forget the dot "." before "fa-bars", so in that way the style is applied to element tag called "fa-bars" which not exists.
- There is no element has class called "fa-bars" in HTML document

2022-04-30 09:43 UTC, Mohammed4mach commented on Master.css
> +      margin-left: 1000px;
### **High** margin values is not recommended

This could cause serious problems in displaying that element and neighboring elements.

Using `display: flex` with its properties is highly recommended instead.

2022-04-30 09:43 UTC, Mohammed4mach commented on Master.css
> +h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6 {
### Do not use element tag as a selector in stylesheet

In a **Master Design** stylesheet, this line has two problems with great effect on further development:
- This will affect displaying every element with the same name in every page that include this CSS file.
- (.h2, .h3, .h4, .h5, .h6) is not class names used in the HTML document.

2022-04-30 09:43 UTC, Mohammed4mach commented on Master.css
> +.text-warning{
### Class name isn't used in HTML

There is no element has class called "text-warning" in HTML document

2022-04-30 09:43 UTC, Mohammed4mach commented on MasterDesign.html
> +
### Why leaving a blank line ?!

same problem at lines  41, 99

2022-04-30 09:43 UTC, Mohammed4mach commented on MasterDesign.html
> +                <a class="nav-link p-lg-3" href="#"> <i class="fa-solid fa-right-to-bracket" style="color:white;"> </i> Sign In</a>
### Inline style, if is not necessary, is considered now as bad practice

All inline style should be moved to external stylesheet.

Same problem at lines 35, 69 and 77

2022-04-30 09:43 UTC, Mohammed4mach commented on MasterDesign.html
> +              <li class="nav-item dropdown">
### \<li\> without its closing tag

2022-04-30 09:44 UTC, Mohammed4mach requested changes
Few changes are required

2022-04-30 11:24 UTC, ManarMagdy commented on MasterDesign.html
> +</html>
for the icons
if you delete it , it wouldn't be working

2022-04-30 11:43 UTC, ManarMagdy commented on Master.css
> +    height: 3000px;
I really knew that later
here, i was trying the scroll
we should add (position : relative;  bottom: 0 ;) to the footer

2022-05-01 04:12 UTC, ManarMagdy commented on Master.css
> +.text-warning{
While making edits I deleted some elements and forgot to remove them from css style as well

2022-05-01 04:15 UTC, ManarMagdy commented on MasterDesign.html
> +              <li class="nav-item dropdown">
done

2022-05-01 22:21 UTC, Mohammed4mach approved these changes

2022-05-01 22:21 UTC, merged